/**
 * Health habit data (energy check-ins, daily metrics, runs) stored in Postgres
 * per user. Sample data is generated by src/mastra/seed. Dates are returned as
 * local YYYY-MM-DD strings.
 */
import { type Ctx, dbOf, userIdOf } from "./demo-user";

export const ENERGY_LEVELS = ["low", "okay", "good", "great"] as const;
export type EnergyLevel = (typeof ENERGY_LEVELS)[number];

/** Numeric score for averaging: low = 1 ... great = 4. */
export const energyScore = (level: EnergyLevel) =>
  ENERGY_LEVELS.indexOf(level) + 1;

export type Checkin = {
  /** Local calendar date, YYYY-MM-DD */
  date: string;
  /** Answer to "How's your energy?" in the daily check-in */
  energy: EnergyLevel;
  note?: string;
};

export type DailyMetrics = {
  date: string;
  steps: number;
  activeMinutes: number;
  hydrationMl: number;
  sleepHours: number;
};

/** Common general wellness reference points used to flag gaps. */
export const TARGETS = {
  hydrationMl: 2000,
  steps: 7000,
  activeMinutes: 30,
  sleepHours: 7,
} as const;

const pad = (n: number) => String(n).padStart(2, "0");
export const isoDate = (daysAgo: number) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
};

const num = (v: unknown) => Number(v);
const DATE = (col: string, as: string) => `to_char(${col}, 'YYYY-MM-DD') AS ${as}`;

const toMetrics = (r: Record<string, unknown>): DailyMetrics => ({
  date: String(r.date),
  steps: num(r.steps),
  activeMinutes: num(r.active_minutes),
  hydrationMl: num(r.hydration_ml),
  sleepHours: num(r.sleep_hours),
});
const toCheckin = (r: Record<string, unknown>): Checkin => ({
  date: String(r.date),
  energy: r.energy as EnergyLevel,
  ...(r.note ? { note: String(r.note) } : {}),
});
const toRun = (r: Record<string, unknown>): Run => ({
  date: String(r.date),
  distanceMi: num(r.distance_mi),
  durationMin: num(r.duration_min),
  paceMinPerMi: Math.round((num(r.duration_min) / num(r.distance_mi)) * 100) / 100,
  ...(r.note ? { note: String(r.note) } : {}),
});

/**
 * Records today's check-in (replacing any earlier one today). Shared by the
 * app and the agent tools, so the agent sees what the user just saved.
 */
export async function saveCheckin(energy: EnergyLevel, note?: string, ctx: Ctx = {}): Promise<Checkin> {
  const date = isoDate(0);
  await dbOf(ctx)(
    `INSERT INTO checkins (user_id, checked_on, energy, note) VALUES ($1, $2::date, $3, $4)
     ON CONFLICT (user_id, checked_on) DO UPDATE SET energy = EXCLUDED.energy, note = EXCLUDED.note`,
    [userIdOf(ctx), date, energy, note ?? null],
  );
  return { date, energy, ...(note ? { note } : {}) };
}

/** Today's metrics row, or zeros if nothing has been logged today. */
export async function getToday(ctx: Ctx = {}): Promise<DailyMetrics> {
  const date = isoDate(0);
  const [row] = await dbOf(ctx)(
    `SELECT ${DATE("day", "date")}, steps, active_minutes, hydration_ml, sleep_hours
     FROM daily_metrics WHERE user_id = $1 AND day = $2::date`,
    [userIdOf(ctx), date],
  );
  return row ? toMetrics(row) : { date, steps: 0, activeMinutes: 0, hydrationMl: 0, sleepHours: 0 };
}

/** Adds water to today's total. */
export async function addHydration(ml: number, ctx: Ctx = {}): Promise<DailyMetrics> {
  await dbOf(ctx)(
    `INSERT INTO daily_metrics (user_id, day, hydration_ml) VALUES ($1, $2::date, $3)
     ON CONFLICT (user_id, day) DO UPDATE SET hydration_ml = daily_metrics.hydration_ml + EXCLUDED.hydration_ml`,
    [userIdOf(ctx), isoDate(0), ml],
  );
  return getToday(ctx);
}

/** The `count` most recent check-ins, newest first. */
export async function getRecentCheckins(count: number, ctx: Ctx = {}): Promise<Checkin[]> {
  const rows = await dbOf(ctx)(
    `SELECT ${DATE("checked_on", "date")}, energy, note FROM checkins
     WHERE user_id = $1 ORDER BY checked_on DESC LIMIT $2`,
    [userIdOf(ctx), count],
  );
  return rows.map(toCheckin);
}

/** The most recent `days` days of metrics, newest first. */
export async function getRecentMetrics(days: number, ctx: Ctx = {}): Promise<DailyMetrics[]> {
  const rows = await dbOf(ctx)(
    `SELECT ${DATE("day", "date")}, steps, active_minutes, hydration_ml, sleep_hours
     FROM daily_metrics WHERE user_id = $1 ORDER BY day DESC LIMIT $2`,
    [userIdOf(ctx), days],
  );
  return rows.map(toMetrics);
}

const avg = (values: number[]) =>
  values.length
    ? Math.round((values.reduce((a, b) => a + b, 0) / values.length) * 10) / 10
    : 0;

export function summarizeCheckins(list: Checkin[]) {
  const counts = { low: 0, okay: 0, good: 0, great: 0 } as Record<EnergyLevel, number>;
  for (const c of list) counts[c.energy] += 1;
  const lowShare = list.length ? counts.low / list.length : 0;
  const observations: string[] = [];
  if (list.length >= 3 && lowShare >= 0.5) {
    observations.push(
      `Energy was reported as low in ${counts.low} of ${list.length} check-ins.`,
    );
  }
  return {
    total: list.length,
    counts,
    averageEnergyScore: avg(list.map((c) => energyScore(c.energy))),
    scale: "1 = low, 2 = okay, 3 = good, 4 = great",
    observations,
  };
}

export function summarizeMetrics(list: DailyMetrics[]) {
  const averages = {
    steps: Math.round(avg(list.map((m) => m.steps))),
    activeMinutes: avg(list.map((m) => m.activeMinutes)),
    hydrationMl: Math.round(avg(list.map((m) => m.hydrationMl))),
    sleepHours: avg(list.map((m) => m.sleepHours)),
  };
  const daysBelowTarget = {
    hydration: list.filter((m) => m.hydrationMl < TARGETS.hydrationMl).length,
    steps: list.filter((m) => m.steps < TARGETS.steps).length,
    activeMinutes: list.filter((m) => m.activeMinutes < TARGETS.activeMinutes).length,
    sleep: list.filter((m) => m.sleepHours < TARGETS.sleepHours).length,
  };
  const observations: string[] = [];
  const n = list.length;
  if (n >= 3) {
    if (averages.hydrationMl < TARGETS.hydrationMl * 0.75) {
      observations.push(
        `Average water intake is about ${averages.hydrationMl} ml/day, well under the ~${TARGETS.hydrationMl} ml general target.`,
      );
    }
    if (averages.steps < TARGETS.steps * 0.75) {
      observations.push(
        `Average steps are about ${averages.steps}/day, under the ~${TARGETS.steps} general target.`,
      );
    }
    if (averages.activeMinutes < TARGETS.activeMinutes * 0.75) {
      observations.push(
        `Average active time is about ${averages.activeMinutes} min/day, under the ~${TARGETS.activeMinutes} min general target.`,
      );
    }
    if (averages.sleepHours < TARGETS.sleepHours - 0.5) {
      observations.push(
        `Average sleep is about ${averages.sleepHours} h/night, under the ~${TARGETS.sleepHours} h general target.`,
      );
    }
  }
  return { days: n, averages, daysBelowTarget, targets: TARGETS, observations };
}

// ---------------------------------------------------------------------------
// Running
// ---------------------------------------------------------------------------

export type Run = {
  /** Local calendar date, YYYY-MM-DD */
  date: string;
  distanceMi: number;
  durationMin: number;
  /** Minutes per mile */
  paceMinPerMi: number;
  note?: string;
};


/** The `count` most recent runs, newest first. */
export async function getRecentRuns(count: number, ctx: Ctx = {}): Promise<Run[]> {
  const rows = await dbOf(ctx)(
    `SELECT ${DATE("ran_on", "date")}, distance_mi, duration_min, note FROM runs
     WHERE user_id = $1 ORDER BY ran_on DESC, id DESC LIMIT $2`,
    [userIdOf(ctx), count],
  );
  return rows.map(toRun);
}

/** Records a run for today. */
export async function saveRun(distanceMi: number, durationMin: number, note?: string, ctx: Ctx = {}): Promise<Run> {
  const date = isoDate(0);
  await dbOf(ctx)(
    "INSERT INTO runs (user_id, ran_on, distance_mi, duration_min, note) VALUES ($1, $2::date, $3, $4, $5)",
    [userIdOf(ctx), date, distanceMi, durationMin, note ?? null],
  );
  return toRun({ date, distance_mi: distanceMi, duration_min: durationMin, note });
}

const daysBetween = (isoA: string, isoB: string) =>
  Math.round(
    (new Date(`${isoA}T12:00:00`).getTime() - new Date(`${isoB}T12:00:00`).getTime()) /
      86_400_000,
  );

export function summarizeRuns(list: Run[]) {
  const totalMiles = Math.round(list.reduce((a, r) => a + r.distanceMi, 0) * 100) / 100;
  const totalMinutes = Math.round(list.reduce((a, r) => a + r.durationMin, 0) * 10) / 10;
  const averagePaceMinPerMi = totalMiles
    ? Math.round((totalMinutes / totalMiles) * 100) / 100
    : 0;
  const longestMi = list.reduce((m, r) => Math.max(m, r.distanceMi), 0);
  const daysSinceLastRun = list[0] ? daysBetween(isoDate(0), list[0].date) : null;
  const spanDays = list.length > 1 ? daysBetween(list[0].date, list[list.length - 1].date) + 1 : 0;
  const runsPerWeek = spanDays ? Math.round((list.length / spanDays) * 7 * 10) / 10 : null;
  const observations: string[] = [];
  if (!list.length) observations.push("No runs logged yet.");
  if (daysSinceLastRun !== null && daysSinceLastRun >= 3) {
    observations.push(`Last run was ${daysSinceLastRun} days ago.`);
  }
  if (runsPerWeek !== null && runsPerWeek < 2) {
    observations.push(`Averaging about ${runsPerWeek} runs per week, under a common 2 to 3 a week starter routine.`);
  }
  if (list.length >= 2 && averagePaceMinPerMi >= 11) {
    observations.push(
      `Easy average pace of about ${averagePaceMinPerMi} min/mi, typical of someone building up fitness.`,
    );
  }
  return {
    total: list.length,
    totalMiles,
    totalMinutes,
    averagePaceMinPerMi,
    longestMi,
    daysSinceLastRun,
    runsPerWeek,
    observations,
  };
}
